### ISSUE TITLE
很好的想法，希望能帮上一些忙

### ISSUE THREAD

**Issue by Young-Lord** [lqzhgood/Shmily#1]
（目前是在维护 Python 的 QQ 聊天记录导出项目，最终计划是支持跨平台的读取&多格式输出，故能否提供一个 Get 的规范以便适配？）
https://github.com/Young-Lord/QQ-History-Backup

https://lqzh.me/Shmily/guide/use/msg.html

**Comment by lqzhgood** [comment]
如果你是指 MobileQQ 的 `Msg` 示例的话，可以直接查看 [Demo](http://demo.shmily.lqzh.me/) F12里面的 msg.json 请求

地址为 `http://demo.shmily.lqzh.me/json/msg/msg.json` 

因为里面隐私的关系，可能被去掉了其中很多字段和数据。

`Msg` 主体结构遵循文档 https://lqzh.me/Shmily/guide/use/msg.html 即可

以下是简版的结构
```js

msg.json = [$msg, $msg, $msg ....]

$msg = {
    // 通用字段 
   "source": "CUST_SOURCE",
    ....

    $CUST_SOURCE: {
         "os":    "Android",
          "raw": { } // "数据的原始样貌"
          "key" : { } //// 解密过程中有帮助的值或备注
          "res": {} // 和 raw  key一一对应, value 为解密后的数据   如未加密则  raw =res
          "data": {} // 前端显示所需要的数据
          "rootPath" ///  /data/ $rootPath /img/123.png 资源文件夹名称
    }

    $Dev: {} // 开发中需要用到的数据，Show 生成数据时会被删除
   }
  ```

具体的 $MobileQQ 的结构 我稍后会写一份放在文档里, 就这两天吧
主要是没找到一个比较好用来前端显示(带折叠) JSON 的库

**Comment by lqzhgood** [comment]
我在解密 [MobieQQ-Android](https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod) 时也参考了您的很多代码

在下方 __解密进度__ 可以看到标识~

在解密相关 code 时您也可以参考对应的代码，java 库的 issue 里面也有一些讨论

共同努力吧~

**Comment by lqzhgood** [comment]
文档补充完了~
