### ISSUE TITLE
添加 PC 端微信支持

### ISSUE THREAD

**Issue by ioqbit** [lqzhgood/Shmily#4]
微信客户端取证，可获取用户个人信息(昵称/账号/手机/邮箱/数据库密钥(用来解密聊天记录))
https://github.com/AdminTest0/SharpWxDump

**Comment by lqzhgood** [comment]
暂不支持, 自己的数据导出还能说得过去, 导出别人的会比较敏感吧~ 与项目初衷相悖

如果是自己的数据可以通过 PC 同步到手机的方式支持,  就没必要再开发 PC 的了.
