### ISSUE TITLE
请问下导出后的文件，聊天记录会不会被清空

### ISSUE THREAD

**Issue by Dlian-Zero** [lqzhgood/Shmily#6]
之前用了WeChatMsg这个项目，把我记录清空了，请问这个有这种情况吗？

**Comment by lqzhgood** [comment]
为啥会清空呀?

我是离线只读导出数据库再处理的哦, 每一步都是 幂等不可变~~
通俗点说, 需要你把数据库拷贝到项目后, 
程序再(只读)导出数据库的表为 JSON, 程序对 表JSON 生成 Msg-JSON. 
遵循不可变, 每一步均产生新的产物, 不修改原产物

所以不影响你的真实数据库.
