### ISSUE TITLE
哈喽哈喽，可以支持抖音吗，感谢

### ISSUE THREAD

**Issue by Shuai-S** [lqzhgood/Shmily#7]
现在好多朋友之间的聊天都在抖音了，但是抖音又没有聊天记录导出，希望支持一下，非常感谢

**Comment by lqzhgood** [comment]
抖音这么猛的嘛~
目前太忙了，没有计划支持  
不过抖音聊天记录现在是服务器云同步，暂时也不会丢

**Comment by Shuai-S** [comment]
抖音聊天很方便的，也方便分享东西。
抖音服务器云同步只同步半年，半年前的换手机就不同步了，我这聊天记录都两年了，真的很需要备份了
或者有什么思路吗？可以分享下思路，我这边自己研究研究也行

**Comment by lqzhgood** [comment]
抖音我都没咋用过....  没啥思路可以提供~~
总的来说先撬数据库 然后解密资源呗.
