### ISSUE TITLE
迫切希望能支持ntqq

### ISSUE THREAD

**Issue by Kooluve** [lqzhgood/Shmily#8]
ntqq都出一年多了，却一直不提供导出功能，而且因为滥用强制更新的流氓行为，用户量应该也不低，那么ntqq导出记录的需求应该是挺高的。
我需要尽可能完整地导出大量记录，但网上找了很久都没有关于ntqq的可行方法，连做这块的项目都几乎找不到，更别提实际好用的。
我现在电脑和手机都是ntqq，存储的消息数据也都是ntqq的。手里的设备和虚拟机都试了装旧版（电脑≤9.7.23，手机≤8.9.58），各种设备来回倒腾，也无法从新版导入到旧版，要么消息严重残缺要么直接识别不到传过去的备份文件。难道没有一直坚持用旧版不更新的话，就毫无办法了吗？

**Comment by lqzhgood** [comment]
https://github.com/lqzhgood/Shmily-Get-MobileQQ-Andriod/issues/26
